sudo: required
services:
  - docker

before_install:
  - docker build -t zhaoshuosve/docker-react -f Dockerfile.dev .


scripts:
  - docker run -e CI=tru zhaoshuosve/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-1-827414381419"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
